apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-back
  name: front-back
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-back
  template:
    metadata:
      labels:
        app: front-back
    spec:
      containers:
      - image: gregory78/13-kubernetes-config_frontend:v1.0
        imagePullPolicy: IfNotPresent
        name: frontend
        env:
          - name: BASE_URL
            value: "http://localhost:9000"
 
      - image: gregory78/13-kubernetes-config_backend:v1.0
        imagePullPolicy: IfNotPresent
        name: backend
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgresql-svc:5432/news"
