apiVersion: v1
kind: Service
metadata:
  name: front-back-service
spec:
  selector:
    app: front-back
  ports:
    - name: frontend
      protocol: TCP
      port: 8000
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP

