apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache-stage
  name: apache-stage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-stage
  template:
    metadata:
      labels:
        app: apache-stage
    spec:
      containers:
        - image: httpd
          imagePullPolicy: IfNotPresent
          name: frontend
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: shared-volume
        - image: alpine
          imagePullPolicy: IfNotPresent
          name: backend
          command: ['sh', '-c', 'while true; do sleep 3600; done']
          volumeMounts:
            - mountPath: /static
              name: shared-volume
      volumes:
        - name: shared-volume
          emptyDir: {}
