apiVersion: v1
kind: Service
metadata:
  name: stage-svc
spec:
  selector:
    app: apache-stage
  ports:
    - name: frontend
      protocol: TCP
      port: 88
      targetPort: 80
  type: ClusterIP

