apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP

