apiVersion: v1
kind: Service
metadata:
    name: postgresql-svc
spec:
    type: ClusterIP
    clusterIP: None
    selector:
        app: postgresql-app
    ports:
      - port: 5432
        protocol: TCP
        targetPort: 5432

