apiVersion: v1
kind: Service
metadata:
  name: prod-svc
spec:
  selector:
    app: apache-prod-frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 88
      targetPort: 80
  type: ClusterIP

